### ISSUE TITLE
Not compatible with Analytics 3.0

### ISSUE THREAD

**Issue by tombogle** [sillsdev/DesktopAnalytics.net#18]
Apparently there was a breaking change in the Analytics API that affects DesktopAnalytics. I tried upgrading Transcelerator to version 3.0, and got this crash:

Msg: Method not found: 'Void Segment.Client.Identify(System.String, Segment.Model.Traits, Segment.Model.Options)'.
Class: System.MissingMethodException
Source: DesktopAnalytics
Assembly: DesktopAnalytics, Version=1.2.4.11, Culture=neutral, PublicKeyToken=null
Stack:    at DesktopAnalytics.Analytics.UpdateSegmentIOInformationOnThisUser()
   at DesktopAnalytics.Analytics..ctor(String apiSecret, UserInfo userInfo, Dictionary`2 propertiesThatGoWithEveryEvent, Boolean allowTracking)
   at DesktopAnalytics.Analytics..ctor(String apiSecret, UserInfo userInfo, Boolean allowTracking)
   at SIL.Transcelerator.TxlPlugin.<>c__DisplayClass9_0.<Run>b__0() in C:\Projects\Transcelerator\Transcelerator\TxlPlugin.cs:line 235
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Thread: Transcelerator
Thread UI culture: en-US
Exception: System.MissingMethodException

--Error Reporting Properties--
Version: 1.3.0.0 (apparent build date: 9/25/2019)
CommandLine: "C:\Windows\Microsoft.NET\Framework\v4.0.30319\AddInProcess32.exe" /guid:9482dd65-04db-4296-b28c-d6ff6b6c64af /pid:19908
CurrentDirectory: C:\Program Files (x86)\Paratext 9
MachineName: SWD-BOGLE-LT
OSVersion: Windows 10 
DotNetVersion: 4.0.30319.42000
WorkingSet: 23429120
UserDomainName: WAXHAW
UserName: Bogle
Culture: en-US
Plugin Name: Transcelerator
Host Application: Paratext 9.0.63.5
KeyboardAdaptors: WinKeyboardAdaptor, KeymanKeyboardAdaptor

**Comment by tombogle** [comment]
I assumed that 2.0.0 would be compatible, but it also failed with the same error.

**Comment by andrew-polk** [comment]
Resolved by #20.
